astronomer/ask-astro

ui/package-lock.json, ui/package.json, ui/src/lib/components/custom/ConsentManager.svelte, ui/src/routes/+layout.svelte
This PR adds the Segment Cookie Consent Manager along with Segment's `analytics.js` for traffic analytics and tag management.
=> Add Segment Cookie Consent Manager for Web Traffic Analytics, Tag Management

ui/src/lib/components/custom/MessageCard.svelte
the old code causes the scrollbar to always be visible on some browsers; setting it to auto ensures that if the content isn't too wide, the scrollbar doesn't show
=> use overflow auto instead of scroll

api/ask_astro/slack/app.py
- The ask astro website is breaking after the changes last night were merged: [error log details](https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22ask-astro-dev%22%0Aresource.labels.location%20%3D%20%22us-central1%22%0A%20severity%3E%3DDEFAULT;pinnedLogId=2023-10-14T00:40:34.836628Z%2F6529e382000cc414f14fa80a;cursorTimestamp=2023-10-14T00:41:47.181973Z;aroundTime=2023-10-14T00:40:34.836628Z;duration=PT1H?hl=en&project=astronomer-success)
- Imports need to be fixed
=> Fix the import paths

.gitignore, README.md, airflow/README.md, api/Dockerfile, api/README.md, scripts/local_dev.py, ui/README.md
closes: #30 
Add a simple script and document to run the API server, UI and generate env template for API server
=> Add basic local dev script

airflow/README.md
check the broken static checks in main branch
=> Fix static check

airflow/dags/monitor/external_trigger.py, airflow/dags/monitor/monitor.py, airflow/requirements.txt
closes: https://github.com/astronomer/ask-astro/issues/39
an example post success and fail service status
=> Add basic monitoring

ui/src/routes/+page.server.ts
If we send an empty string, the UI returns 500 error.
The AI asks what it can help which seems to be a more user-friendly response
closes: #82
=> fix(ui): fix 500 on empty prompt

.circleci/config.yml, api/ask_astro/app.py, api/ask_astro/chains/answer_question.py, api/ask_astro/clients/weaviate_.py, api/ask_astro/rest/controllers/__init__.py, api/ask_astro/rest/controllers/get_request.py, api/ask_astro/rest/controllers/list_recent_requests.py, api/ask_astro/rest/controllers/post_request.py, api/ask_astro/rest/controllers/submit_feedback.py, api/ask_astro/services/questions.py, api/ask_astro/slack/app.py, api/ask_astro/slack/controllers/__init__.py, api/ask_astro/slack/controllers/feedback/bad.py, api/ask_astro/slack/controllers/feedback/good.py, api/ask_astro/slack/controllers/mention.py, api/ask_astro/stores/__init__.py, api/poetry.lock, api/pyproject.toml, tests/api/ask_astro/chains/test_answer_questions.py, tests/api/ask_astro/clients/test_firestore.py, tests/api/ask_astro/clients/test_langsmith_.py, tests/api/ask_astro/models/test_request.py, tests/api/ask_astro/rest/controllers/conftest.py, tests/api/ask_astro/rest/controllers/test_get_requests.py, tests/api/ask_astro/rest/controllers/test_list_recent_requests.py, tests/api/ask_astro/rest/controllers/test_post_request.py, tests/api/ask_astro/rest/controllers/test_submit_feedback.py
- Add unit tests for APIs, models
closes: #36
=> Add unittests

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
- Add github template for issues and bug reporting
closes: #91
=> Add github template for issues and bug reporting

docs/README.md, docs/api/README.md, docs/api/cloudbuild_and_run.md, docs/index.md, docs/local_development.md, docs/task_help_text/api_init_poetry_env.md, docs/task_help_text/api_run_with_docker.md, docs/task_help_text/api_run_with_poetry.md, docs/task_help_text/api_stop_container.md, docs/task_help_text/docs_build.md, docs/task_help_text/docs_serve.md, docs/task_help_text/list_tasks.md, docs/task_help_text/ui_init.md, docs/task_help_text/ui_run.md, docs/ui/README.md, tasks/__init__.py, tasks/api.py, tasks/common.py, tasks/docs.py, tasks/ui.py
* Reorganize tasks and add ui server-related tasks. now it looks like the following
```sh
$ poetry run inv -l
Available tasks:
api.init-poetry-env   Initialize the ask-astro API server local poetry environment
api.run-with-docker   Run ask-astro API server with docker
api.run-with-poetry   Run ask-astro API server with poetry
api.stop-container    Stop ask-astro API server container
docs.build            Build sphinx docs
docs.serve            Serve the docs locally (http://127.0.0.1:8000)
ui.init               Initialize UI server dependencies
ui.run                Run UI server
```
* fix doc missing links
fix #45
=> Reorganize tasks

airflow/dags/monitor/monitor_ingestion_dags.py
closes: https://github.com/astronomer/ask-astro/issues/118
Sample alert
=> Add dag to check ingestion dag health

.circleci/config.yml, .readthedocs.yaml, poetry.lock, pyproject.toml
* circleci
* add build-docs step for check doc building process
* use python 3.11 for consistency
* readthedocs
* add readthedocs config
close #94
=> Setup readthedocs and CI job for checking documentation building

.circleci/config.yml
Close: #122 
I think the last step we need is 
> Now, we need to upload the public key to GitHub so that it knows to trust a connection from CircleCI initiated with our private key. We head to https://github.com/jklukas/docs-on-gh-pages/settings/keys > Add Deploy Key, make the title of it “CircleCI write key” and paste in the contents of docs_deploy_key_rsa.pub. If you haven’t already deleted the private key, be extra careful you’re not accidentally copying from docs_deploy_key_rsa!
which might need @sunank200 's help on setting this up. (Scheduled messages with info and instructions for this setup on Slack)
ref: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
=> ci(circleci): setup deploy-docs job

.circleci/config.yml, api/poetry.lock, poetry.lock, pyproject.toml, tasks/__init__.py, tasks/api.py
closes: #89 
it depends on https://github.com/astronomer/ask-astro/pull/96
=> Move tests command to task py

airflow/dags/ingestion/ask-astro-load-registry.py
- Use `AskAstroWeaviateHook` as the taskflow API for [ask-astro-load-registry.py](https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-registry.py)
closes: #138
=> Use AskAstroWeaviateHook for ask-astro-load-registry.py DAG

airflow/dags/ingestion/ask-astro-load-blogs.py
- Use `AskAstroWeaviateHook` as the taskflow API for [ask-astro-load-blogs.py](https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-blogs.py)
closes: #135
=> Use AskAstroWeaviateHook for ask-astro-load-blogs.py

.pre-commit-config.yaml, airflow/ruff.toml, api/ask_astro/config.py, api/ask_astro/services/questions.py, pyproject.toml
* style(api): format through ruff
* build(pre-commit): setup ruff formatted
closes: #163
=> Setup ruff formater

airflow/include/tasks/extract/blogs.py
When parsing links, parse the article tag to get the date to filter. Break the loop if any dates are filtered in an iteration.
closes: #116
=> refactor(airflow): refactor extract_astro_blogs method

airflow/dags/ingestion/ask-astro-load-astro-cli.py, airflow/dags/ingestion/ask-astro-load.py, airflow/include/tasks/extract/astro_cli_docs.py
=> feat(airflow): add astro-cli ingestion

airflow/dags/ingestion/ask-astro-load-astro-sdk.py, airflow/dags/ingestion/ask-astro-load-astronomer-provider.py, airflow/dags/ingestion/ask-astro-load.py, airflow/include/tasks/extract/astro_sdk_docs.py, airflow/include/tasks/extract/astronomer_providers_docs.py, airflow/include/tasks/extract/utils/html_url_extractor.py
closes: https://github.com/astronomer/ask-astro/issues/166
closes: https://github.com/astronomer/ask-astro/issues/165
=> Ingest astronomer-provider/astro-sdk html docs

docs/README.md
We do not include slack data in our production because PII restriction 
so I feel it makes sense to remove this from README too
=> Remove slack reference from README

airflow/dags/ingestion/ask-astro-load-stackoverflow.py, airflow/dags/ingestion/ask-astro-load.py, airflow/include/tasks/extract/stack_overflow.py, airflow/include/tasks/extract/utils/stack_overflow_helpers.py, airflow/requirements.txt
refactor https://github.com/astronomer/ask-astro/commit/47933b52dc8da905fdbb4fe1627d35f1254a98a7 and make it consistent with existing archive logic
closes: #126
=> Add stack overflow ingest

ui/src/lib/components/custom/SourceCard.svelte
Closes: #184
The root cause of this issue is that the default style of h1 contains `text-align: center;`. This PR overwrites this behavior
=> fix(ui): fix h1 text alignment

airflow/dags/ingestion/ask-astro-load-github.py, airflow/dags/ingestion/ask-astro-load.py, airflow/include/tasks/extract/github.py
closes: https://github.com/astronomer/ask-astro/issues/227
Recently, we started getting zombie job and I feel this because of lot of data on worker
=> Add a cutoff date for GitHub issue

api/ask_astro/app.py, api/ask_astro/rest/controllers/__init__.py, tests/api/ask_astro/rest/controllers/conftest.py, ui/src/routes/+page.server.ts, ui/src/routes/requests/[request_id]/+page.server.ts
Throttles API requests based on user's IP address. 
With this PR, at the moment, we are only throttling `/requests` endpoint.
closes: #230
=> Use sanic-limiter to throttle api requests

api/ask_astro/rest/controllers/get_request.py, tests/api/ask_astro/rest/controllers/test_get_requests.py
The UI renders the response from ask-astro pipeline as a markdown. 
For list items, the UI is able to render the list properly when the 
list items are separated by `\n\n` in the backend response, however 
when the list items are separated by a single `\n`, it fails to render 
them correctly. It's weird how OpenAI completion response at times 
adds a double new line chars and at times adds a single new line 
char to separate list items. However, I am adding a transform to 
convert single new line chars to double and when the response 
already contains two new line chars, not adding any extra new line char.
closes: #215
=> Improve readibility of list results

airflow/include/tasks/extract/utils/weaviate/ask_astro_weaviate_hook.py
Currently, if ingestion fail we get some error and while logging if error is not string it throw error doing string concatenation 
**Log After this change**
```
[{'uuid': '0a89e583-6260-5c6c-9f9c-7b5a90db3d7b', 'errors': {'error': [{'message': "update vector: connection to: OpenAI API failed with status: 400 error: This model's maximum context length is 8192 tokens, however you requested 8236 tokens (8236 in your prompt; 0 for the completion). Please reduce your prompt; or completion length."}]}}, {'uuid': '5fa895fe-adc1-5303-8a1e-e9fe9b06d88b', 'errors': {'error': [{'message': "update vector: connection to: OpenAI API failed with status: 400 error: This model's maximum context length is 8192 tokens, however you requested 8290 tokens (8290 in your prompt; 0 for the completion). Please …
```
=> Log weaviate client error string joining

airflow/dags/ingestion/ask-astro-load-astronomer-docs.py, airflow/dags/ingestion/ask-astro-load-github.py, airflow/dags/ingestion/ask-astro-load.py, airflow/dags/monitor/monitor_ingestion_dags.py, airflow/include/tasks/extract/astro_docs.py
- Create a separate DAG to scrap astronomer docs.
- Link astro docs to the webpage, not GitHub.
- Change all existing DAGs.
- Tested the ingestion [here](https://clmkpsyfc000301kcjie00t1l.astronomer.run/d2gj0n9c/dags/ask_astro_load_astronomer_docs/grid?dag_run_id=manual__2023-12-28T10%3A06%3A33.435906%2B00%3A00&task_id=ingest_data&tab=logs&map_index=0)
closes: #129
=> Link Astro docs to the webpage not github

airflow/dags/feedback/find_example_runs.py, airflow/dags/ingestion/ask-astro-forum-load.py, airflow/dags/ingestion/ask-astro-load-airflow-docs.py, airflow/dags/ingestion/ask-astro-load-astro-cli.py, airflow/dags/ingestion/ask-astro-load-astro-sdk.py, airflow/dags/ingestion/ask-astro-load-astronomer-docs.py, airflow/dags/ingestion/ask-astro-load-astronomer-provider.py, airflow/dags/ingestion/ask-astro-load-blogs.py, airflow/dags/ingestion/ask-astro-load-github.py, airflow/dags/ingestion/ask-astro-load-registry.py, airflow/dags/ingestion/ask-astro-load-slack.py, airflow/dags/ingestion/ask-astro-load-stackoverflow.py, airflow/dags/ingestion/ask-astro-load.py, airflow/dags/monitor/external_trigger.py, airflow/dags/monitor/monitor.py, airflow/dags/monitor/monitor_ingestion_dags.py, airflow/include/utils/slack.py
The PR adds `on_failure_callback` for all the Ask Astro DAGs 
to notify DAG failures to the desired alerts Slack channel by leveraging 
the Slack Notifier from the Apache Airflow Slack provider.
For the alerts to work, it will need a connection of type `slack` 
created in the deployment. If the connection ID for this connection 
is different than the default `slack_api_default`, then the 
connection ID needs to be set in the deployment as an environment 
variable named `ASK_ASTRO_ALERT_SLACK_CONN_ID`.
closes: #231
=> Send Slack alerts for DAG failures

api/ask_astro/slack/controllers/mention.py
- Add a fix so that the Slackbot should receive the source documents in the same order as they appear in the UI.
closes: #250 
Tested it here:
Slack request: [https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1704903223475919](https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1704903223475919)
Web UI request: [https://f9c33f8b.ask-astro.pages.dev/requests/48c82d1e-afd1-11ee-a80f-42004e494300](https://f9c33f8b.ask-astro.pages.dev/requests/48c82d1e-afd1-11ee-a80f-42004e494300)
=> Return the source documents in same order for slackbot as per the response in the UI 

api/ask_astro/rest/controllers/get_request.py
After asking questions in ask.astronomer.io the UI broke after this [PR](https://github.com/astronomer/ask-astro/pull/240) as there is no check for `"response"` key in the returned dictionary [here](https://github.com/astronomer/ask-astro/blob/main/api/ask_astro/rest/controllers/get_request.py#L46)
Added the check for the "response" key in the dictionary in the API.
Tested with the following screenshot:
close: #266
=> check if dictionary has a response key on_get_request

airflow/include/tasks/extract/astro_forum_docs.py, airflow/include/tasks/extract/utils/html_utils.py
- Context: See here #262 
- Note: this is a quick turnaround fix. Will need to look into better retry logic long term down the road and potentially write a wrapper for the requests.
- Added wait time between calls so we don't get 429 error when web scrapping in our DAGs.
- Added timeout of 1 sec at a few spots
- Added user agent in requests header ([see reason here](https://stackoverflow.com/a/40393773))
- We can also do exponential backoff retry as an alternative if that route is preferred
fixes #262
=> [Quick Fix] Add wait time between web scrapping requests

api/ask_astro/chains/answer_question.py, api/ask_astro/chains/custom_llm_output_lines_parser.py, pyproject.toml
- See https://github.com/astronomer/ask-astro/issues/272 for details of why the error occurs. This won't be explained again in this PR.
- This PR tackles the problem where the `LineListOutputParser` used in LangChain's `MultiQueryRetriever` not cleaning enough edge cases such as empty lines generated from LLM between reworded prompt lines causing an error thrown downstream (the empty line, along with other 2 reworded prompts are individually sent downstream to be used for vector db documents retrieval but an empty string will error out during this phase).
- Add `CustomLineListOutputParser`, a modified, less error prone implementation of the LineListOutputParser from LangChain. This CustomLineListOutputParser will get rid of lines that are empty lines and also limits the max number of …
=> Fix MultiQueryRetriever Prompt Rewording Inconsistent Formatting Error

airflow/include/tasks/extract/airflow_docs.py
- See https://github.com/astronomer/ask-astro/issues/282 for details of why the error occurs. This won't be explained again in this PR.
- TL;DR: A previous refactor PR deleted parts where we convert a set of URLs for airflow docs into a list of dataframes containing the actual docs.
- Added previous incorrectly deleted code back (from this PR https://github.com/astronomer/ask-astro/pull/237/files#diff-a9a4a2183823324d52b3b700e73457392b9117a8fdbd252621e8d4d2f10b2ec1, and this file https://github.com/astronomer/ask-astro/blob/f0967a60ac8e37b8d3885940d636b2b381d36e4e/airflow/include/tasks/extract/airflow_docs.py)
- Previously
- Now
closes #282
=> Fix Airflow Doc Ingestion Task Incorrect Typing Error

api/ask_astro/app.py, api/ask_astro/rest/controllers/__init__.py, tests/api/ask_astro/rest/controllers/conftest.py, ui/package-lock.json, ui/package.json, ui/src/routes/+page.server.ts
- See https://github.com/astronomer/ask-astro/issues/268 for details of why the error occurs. This won't be explained again in this PR.
- TL;DR: svelte backend (cloudflare) is sitting in front of the GCP API therefore it is not possible to do IP based rate limiting in sanic. Instead, we must implement it in svelte for now.
- In production environment, I have set cookie rate limit to be 5 requests per minute, and IP based rate limit to be 100 per day using cloudflare's environment varables
- Add sveltekit-rate-limiter
- Revert the old PR that caused the rate limit issue (where all requests are misinterpreted as the same IP)
Setup:
- In Cloudflare, I have set the dev environment to temporarily have these environment varaibles
1. Test cookie rate limiter. This should trigger after 5 requests …
=> Add sveltekit-rate-limiter & Fix Rate Limiter Issue

api/ask_astro/chains/answer_question.py, api/ask_astro/clients/weaviate_.py, api/ask_astro/config.py
- We have now migrated Ask Astro credentials into a single account on Azure. All OpenAI model deployments now use the same Azure endpoint (US East 2) and credentials. Therefore, the US East credentials environment variable and the config field is no longer relevant.
- New credentials already tested in dev servers. `AZURE_OPENAI_USEAST_PARAMS` and `AZURE_OPENAI_USEAST2_PARAMS` was set to the be same
- In this branch, I removed the environment variable for `AZURE_OPENAI_USEAST_PARAMS` and the service still worked as expected.
Related to Issue #197 (Azure OpenAI migration, not OpenAI)
=> Remove Azure US East Config and Credentials

api/ask_astro/models/request.py, api/ask_astro/rest/controllers/post_request.py, api/ask_astro/services/questions.py, api/ask_astro/slack/controllers/mention.py, tests/api/ask_astro/models/test_request.py
The PR makes the following changes:
1. Updates the request object to include a client variable to capture information on which client is sending the request. This information will be used to update the prompt & also for capturing metrics on requests per client type. Currently there are two client types - slack & webapp
2. For each of the client types - slack and webapp, we add conditions to update the relevant request variable
3. When the request is received from a webapp, then the prompt to LLM is updated to specify that we must return the result in markdown format
=> Bugfix: Added changes to update prompt for webapps

api/ask_astro/templates/combine_docs_chat_prompt.txt
- Updates system prompt so that when not enough useful information in the docs are supplied to the LLM call, the LLM may be allowed to generate an answer on it's own but must warn user about potential inaccuracies
- Updates system prompt so that when topics regarding commercial usage and pricing of astronomer is brought up, the user is prompted to talk to customer support instead.
- No significant changes to quality expected
- Results to be posted
closes #299
=> Update System Prompt to Avoid Discussion of Unwanted Topics & Warn Users About Hallucinations

ui/src/routes/+page.server.ts
* Fix Example Requests Cards Not Showing on UI
* Bug introduced in 0.3.0 release
This is already deployed and is working
=> [Hotfix] Fix Example Requests Cards Not Showing on UI

api/ask_astro/services/questions.py
Just 1 line of code change. PR is self explanatory.
This is causing an issue in prod and new branch has been tested where it does not error out
=> [Hotfix] Slack Message History Not Being Passed Introduced by Another Hotfix During 0.3.1

airflow/dags/metrcis/load_firestore_to_snowflake.py
- `response_received_at` is a nullable field. Specifically, if a request errored out, then this field is null.
- Changing to put `sent_at` field into snowflake's `created_at` column instead
- Tested manually on dev server
Verified in snowflake
=> Change Firestore Metric Field Name to Load into Snowflake

airflow/include/tasks/extract/github.py
Hello - this PR adjusts the regexes found in `airflow/include/tasks/extract/github.py` that remove boilerplate text from GitHub issue thread text. Before this change, the regular expressions will remove too much text due to the greedy matching.
Consider the following example:
```
Discussion here.
More discussion here.
Even more discussion here
```
The two lines containing comments should be removed, but the greedy match in the regular expression `` will cause the line `More discussion here.` to be removed as well.
To fix that behavior, this PR replaces each greedy `.*` sequence with a lazy `.*?` sequence so that the minimum (intended) match is removed.
=> Regex update to avoid over-redaction of GitHub issues
