astronomer/ask-astro

airflow/dags/ingestion/ask-astro-load.py
closes: https://github.com/astronomer/ask-astro/issues/44
=> Add conditional schedule_interval and comment out slack task for ask-astro-load DAG

docs/api/setup_slack_bot.md
- Add Interactivity & Shortcuts step to slack documentation
=> Add Interactivity & Shortcuts step to slack documentation

.gitignore
- [https://astronomer.slack.com/archives/C05QJA9LTR9/p1698931456824639](https://astronomer.slack.com/archives/C05QJA9LTR9/p1698931456824639)
=> Update .gitignore to include UI code

api/ask_astro/slack/controllers/feedback/bad.py, api/ask_astro/slack/controllers/feedback/good.py
This PR change bot response to feedback in the thread 
closes: https://github.com/astronomer/ask-astro/issues/88
=> Change bot response to feedback in the thread and make is visible to all

ui/src/lib/components/custom/MessageCard.svelte, ui/src/routes/requests/[request_id]/+page.svelte
closes: https://github.com/astronomer/ask-astro/issues/99
=>  feat(ui): hide feedback when error occurs 

docs/README.md
- Add build story for Ask-Astro documentation
closes: #72
=> Add build story for Ask-Astro

airflow/dags/ingestion/ask-astro-load-slack.py
- Use `AskAstroWeaviateHook` as the taskflow API for [ask-astro-load-slack.py](https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-slack.py)
closes: #140
=> Use AskAstroWeaviateHook for ask-astro-load-slack.py DAG

airflow/dags/ingestion/ask-astro-load-stackoverflow.py
- Use `AskAstroWeaviateHook` as the taskflow API for [ask-astro-load-stackoverflow.py](https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-stackoverflow.py)
closes: #139
=> Use AskAstroWeaviateHook for ask-astro-load-stackoverflow.py DAG

airflow/dags/ingestion/ask-astro-load-github.py
- Use `AskAstroWeaviateHook` as the taskflow API for [ask-astro-load-github.py](https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-github.py)
closes: #137
=> Use AskAstroWeaviateHook for ask-astro-load-github.py DAG

ui/src/routes/requests/[request_id]/+page.svelte
How to fix and why the issue occurs: https://svelte.dev/tutorial/keyed-each-blocks
closes: #83
=> fix(ui): fix message card rendering issue

api/ask_astro/services/questions.py, api/poetry.lock, api/pyproject.toml
Retry if an exception is encountered while answering a question. 
closes: #167
closes: #179
=> Retry question answering failure

airflow/dags/feedback/find_example_runs.py
closes https://github.com/astronomer/ask-astro/issues/106
retry is only missing for feedback dag so adding it
=> Add retry in feedback dag

airflow/dags/ingestion/ask-astro-load.py, airflow/include/tasks/extract/utils/weaviate/ask_astro_weaviate_hook.py
- Fix pre-commit issues issues in main
=> Fix pre-commit issues

airflow/include/tasks/extract/github.py
closes: https://github.com/astronomer/ask-astro/issues/113
=> Extract all GH issue for ingestion

docs/_static/images/task_help_message/airflow-run.svg, docs/_static/images/task_help_message/airflow-stop.svg, docs/_static/images/task_help_message/api-test.svg, docs/_static/images/task_help_message/list-tasks.svg, docs/_static/images/task_help_message/run-pre-commit.svg, docs/airflow/README.md, docs/index.md, docs/local_development.md, docs/ui/README.md, tasks/__init__.py, tasks/airflow.py
* docs: add missing task help command and fix incorrect image path
* build(tasks): add airflow tasks `inv airflow.start`, `inv airflow.stop`
closes: #202
=> Add airflow tasks

airflow/dags/monitor/monitor_ingestion_dags.py
Recently added some ingestion DAGs are not in monitoring DAG. This PR include them
=> Add missing ingestion DAG in monitoring

airflow/dags/ingestion/ask-astro-load.py
- Removed the astro-sdk ingestion as per suggestion with Steven
More details at: [slack thread](https://astronomer.slack.com/archives/C06CGUXM0LE/p1704489285398289)
=> Remove astro-sdk ingestion

airflow/dags/monitor/test_retrieval.py
closes: https://github.com/astronomer/ask-astro/issues/255
looks like test_retrieval is still trying to use `AskAstroWeaviateHook` which does not exist any more
=> Fix retrieval dag by removing AskAstroWeaviateHook

CODEOWNERS
Adding myself to the CODEOWNERs to help with the project owner transition
=> Add David to CODEOWNERS

airflow/dags/ingestion/ask-astro-forum-load.py, airflow/dags/ingestion/ask-astro-load-airflow-docs.py, airflow/dags/ingestion/ask-astro-load-astro-cli.py, airflow/dags/ingestion/ask-astro-load-astro-sdk.py, airflow/dags/ingestion/ask-astro-load-astronomer-docs.py, airflow/dags/ingestion/ask-astro-load-astronomer-provider.py, airflow/dags/ingestion/ask-astro-load-blogs.py, airflow/dags/ingestion/ask-astro-load-github.py, airflow/dags/ingestion/ask-astro-load-registry.py, airflow/dags/ingestion/ask-astro-load-slack.py, airflow/dags/ingestion/ask-astro-load-stackoverflow.py
- See issue https://github.com/astronomer/ask-astro/issues/281
- Changed interval to be read from environment variable instead
- Defaults to weekly Tuesday at 5
closes #281
=> Change Ingestion Schedule Interval to Weekly

docs/README.md, docs/airflow/README.md, docs/index.md, docs/local_development.md, docs/monitoring.md, ui/src/routes/+layout.svelte
Airflow got its R this weekend :)
Devlist message: https://lists.apache.org/thread/0fmp9olljfkm3vmg3ns5qd1o95sm7235
Guidelines: https://www.apache.org/foundation/marks/guide#naming
=> Add trademarking to Apache Airflow/Airflow where relevant
